// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/go-tab/BottomBarPreview.tsx": () => import("../components/mockups/go-tab/BottomBarPreview.tsx"),
  "./components/mockups/ride-sheets/CancelFlow.tsx": () => import("../components/mockups/ride-sheets/CancelFlow.tsx"),
  "./components/mockups/ride-sheets/DriverAccepted.tsx": () => import("../components/mockups/ride-sheets/DriverAccepted.tsx"),
  "./components/mockups/ride-sheets/DriverChat.tsx": () => import("../components/mockups/ride-sheets/DriverChat.tsx"),
  "./components/mockups/ride-sheets/RideInProgress.tsx": () => import("../components/mockups/ride-sheets/RideInProgress.tsx"),
  "./components/mockups/ride-sheets/RideSelectSheet.tsx": () => import("../components/mockups/ride-sheets/RideSelectSheet.tsx"),
  "./components/mockups/ride-sheets/SearchingSheet.tsx": () => import("../components/mockups/ride-sheets/SearchingSheet.tsx"),
  "./components/mockups/ride-sheets/TripCompleted.tsx": () => import("../components/mockups/ride-sheets/TripCompleted.tsx")
};
