// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/go-tab/BottomBarPreview.tsx": () => import("../components/mockups/go-tab/BottomBarPreview.tsx")
};
